In [1]:
import numpy as np
from scipy import ndimage, misc

In [44]:
class Game:
    def __init__(self, print_game):
        self.grid = np.zeros((4,4), dtype=np.int64)
        self.p = print_game
        self.addrandom(2)

        # print options
        if self.p==True: print(self.grid)

    def addrandom(self, k):
        # Find all empty indeces  
        emptyIndeces  = [i for i, val in enumerate(self.grid.flatten()) if val == 0]

        # Call game over
        if len(emptyIndeces) == len(self.grid.flatten):
            raise Exception("= = = GAME OVER = = =" )
        
        for _ in range(k):
            # Draw index from empty indeces
            index = np.random.choice(emptyIndeces)
            i, j = int(index/4), index-int(index/4)*4
            # Add number on that index
            self.grid[i,j] = 2

    def move(self, direction):
        # 0 = down
        # 1 = up
        # 2 = left
        # 3 = right
        if direction==0: temp_grid = self.grid
        if direction==1: temp_grid = self.grid[::-1]
        if direction==2: temp_grid = ndimage.rotate(self.grid,90)
        if direction==3: temp_grid = ndimage.rotate(self.grid,-90)

        for i in range(4):
            temp_grid[:,i] = self.merge(temp_grid[:,i])

        if direction==0: self.grid = temp_grid
        if direction==1: self.grid = self.grid[::-1]
        if direction==2: self.grid = ndimage.rotate(temp_grid,-90)
        if direction==3: self.grid = ndimage.rotate(temp_grid, 90)

        # Add new value
        self.addrandom(1)

        # print options
        if self.p==True: print(self.grid)


    def merge(self, column):
        tracker = [False]*len(column)
        column = column[::-1]
        for i in range(1,4):
            for j in range(i-1,-1,-1):
                if column[j]==column[j+1] and column[j]!=0 and tracker[j]==False and tracker[j+1]==False:
                    column[j]+=column[j]
                    column[j+1]=0
                    tracker[j]=True
                if column[j]==0 and column[j+1]!= 0:
                    column[j]=column[j+1]
                    column[j+1]=0
                    tracker[j+1] = False
                    tracker[j] = tracker[j+1]

        return column[::-1]

In [43]:
g = Game(True)
directions = {
        0: "down",
        1: "up",
        2: "left",
        3: "right"
        }
for i in range(100):
    n = np.random.randint(4)
    print(directions[n])
    g.move(n)

[[0 0 0 0]
 [0 0 0 0]
 [2 0 0 0]
 [0 0 2 0]]
up
[[0 0 2 0]
 [2 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 2 0]
 [2 0 2 0]]
right
[[2 0 0 0]
 [0 0 0 0]
 [2 2 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [2 0 0 4]]
right
[[2 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [4 2 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [2 0 2 4]]
down
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [2 0 2 4]]
[[0 2 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [2 0 2 4]]
down
[[0 2 0 0]
 [0 0 0 0]
 [0 0 0 2]
 [2 0 2 4]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 2 2]
 [2 2 2 4]]
up
[[2 2 2 4]
 [0 0 2 2]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 2 4]
 [2 2 4 2]]
left
[[0 0 4 2]
 [0 0 2 4]
 [0 0 0 2]
 [0 0 0 2]]
[[0 2 0 0]
 [0 0 0 0]
 [2 4 0 0]
 [4 4 2 0]]
left
[[0 0 0 0]
 [0 0 0 2]
 [2 0 4 4]
 [0 0 2 4]]
[[2 0 0 0]
 [0 0 0 2]
 [2 4 0 0]
 [8 2 0 0]]
left
[[0 2 0 0]
 [0 0 0 0]
 [0 0 4 2]
 [2 0 2 8]]
[[2 0 0 0]
 [2 0 0 0]
 [2 4 0 0]
 [8 2 0 2]]
left
[[0 0 0 2]
 [0 0 0 0]
 [0 0 4 2]
 [2 2 2 8]]
[[2 2 0 0]
 [2 0 0 0]
 [2 4 0 0]
 [8 4 0 0]]
down
[[

In [39]:
g = Game(0)
g.grid = np.array([[ 0,  0,  0,  0],
 [ 0,  2,  0 , 4],
 [ 0,  0,  0,  2],
 [ 16, 16,  8,  0]])

print(g.grid[::-1])
g.move(1)
print(g.grid)



[[16 16  8  0]
 [ 0  0  0  2]
 [ 0  2  0  4]
 [ 0  0  0  0]]
[[0 8 0 0]
 [2 0 0 0]
 [4 0 2 0]
 [0 0 0 0]]
[[0 2 8 4]
 [0 0 0 2]
 [0 0 0 0]
 [2 0 0 0]]
