In [12]:
import numpy as np
from scipy import ndimage, misc
from deap import base
from deap import creator
from deap import tools
import game

In [8]:
n_weights = 9
population_size = 10

In [9]:
''' DEAP SETUP '''
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, fitness=creator.FitnessMin)

toolbox = base.Toolbox()
toolbox.register("attr_bool", np.random.uniform, 0, 1)
toolbox.register("individual", tools.initRepeat, creator.Individual, 
    toolbox.attr_bool, n_weights)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

C:\Users\44741\anaconda3\envs\NIC\lib\site-packages\deap\creator.py:141: RuntimeWarning: A class named 'FitnessMin' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
C:\Users\44741\anaconda3\envs\NIC\lib\site-packages\deap\creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)


In [11]:
# Create the population
population = toolbox.population(population_size)

# One individual (9 random weights)
population[0]

[0.7912074744682034,
 0.43401511522115077,
 0.3155731125801652,
 0.16989018702282233,
 0.9771363152171468,
 0.23122138611847864,
 0.41377201168195554,
 0.9712181101827779,
 0.8785046965188444]

In [16]:
# Start 2048 game
game_sample = game.Game(print_game=True)

[[0 0 0 2]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 2]]


In [17]:
# Move down
game_sample.move(0)

[[2 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 4]]
